let trainingPath='', folder=null, progress={}, collections={favorites:[],playlists:[]};
const $=s=>document.querySelector(s), media=new Set(['mp4','webm','ogv','m4v','mov','mkv','avi','flv','wmv','mpeg','mpg','ts','m2ts','3gp']), audio=new Set(['mp3','wav','ogg','m4a','flac']), images=new Set(['jpg','jpeg','png','gif','webp','svg']), embedded=new Set(['pdf','txt','md','csv','json','html','htm']);
const bytes=v=>v?new Intl.NumberFormat(undefined,{notation:v>999999?'compact':'standard',maximumFractionDigits:1}).format(v)+' B':'0 B', time=s=>{const n=Math.floor(s||0);return `${Math.floor(n/60)}m ${String(n%60).padStart(2,'0')}s`;}, escape=v=>{const e=document.createElement('span');e.textContent=v;return e.innerHTML;}, url=item=>`/files?path=${encodeURIComponent(item.path)}`;
function meta(item){const watched=progress[item.path];if(item.kind==='folder')return'Folder';if(media.has(item.extension)&&watched)return watched.duration&&watched.position>=watched.duration-5?`${item.extension} · completed`:`${item.extension} · watched ${time(watched.position)}`;return`${item.extension||'file'} · ${bytes(item.size)}`}
function compare(a,b){const mode=$('#sort').value;if(mode==='name')return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'});if(mode==='modified')return b.modified.localeCompare(a.modified)||a.name.localeCompare(b.name);if(mode==='size')return b.size-a.size||a.name.localeCompare(b.name);const ak=a.kind==='folder'?'0-folder':`1-${a.extension||'other'}`,bk=b.kind==='folder'?'0-folder':`1-${b.extension||'other'}`;return ak.localeCompare(bk)||a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})}
const isFavorite=item=>collections.favorites.some(favorite=>favorite.path===item.path);
function itemIcon(item){return item.kind==='folder'?'▰':media.has(item.extension)?'▶':audio.has(item.extension)?'♪':images.has(item.extension)?'▧':'•'}
function actions(item){return `<span class="card-actions"><button class="collection-action favorite-action" type="button" title="${isFavorite(item)?'Remove from favorites':'Add to favorites'}">${isFavorite(item)?'★':'☆'}</button><button class="collection-action playlist-action" type="button" title="Add to a playlist">＋</button></span>`}
function renderFolder(){if(!folder)return;const term=$('#search').value.trim().toLowerCase(),items=folder.entries.filter(item=>!term||item.name.toLowerCase().includes(term)).sort(compare),catalog=$('#catalog');catalog.replaceChildren();items.forEach(item=>{const card=document.createElement('article');card.tabIndex=0;card.className=`item-card ${item.kind}`;card.innerHTML=`<span class="item-icon" aria-hidden="true">${itemIcon(item)}</span><span class="item-main"><strong>${escape(item.name)}</strong><small>${escape(meta(item))}</small></span>${actions(item)}${item.kind==='folder'?'<span class="chevron" aria-hidden="true">›</span>':''}`;card.onclick=e=>{if(e.target.closest('.favorite-action'))return toggleFavorite(item);if(e.target.closest('.playlist-action'))return addToPlaylist(item);showItem(item)};card.onkeydown=e=>{if(e.key==='Enter')showItem(item)};catalog.append(card)});$('#empty').hidden=items.length!==0;$('#folder-summary').textContent=`${items.length} shown of ${folder.entries.length} visible items · refreshed ${new Date(folder.refreshedAt).toLocaleTimeString()}`}
function breadcrumbs(){const nav=$('#breadcrumbs');nav.replaceChildren();if(!folder)return;const bits=folder.path.replaceAll('/','\\').split('\\').filter(Boolean);let path=bits[0]?.endsWith(':')?`${bits[0]}\\`:'';bits.forEach((bit,index)=>{if(index>0)path+=`${bit}\\`;const target=index===0?`${bit}\\`:path.replace(/\\$/,'');const crumb=document.createElement('button');crumb.type='button';crumb.textContent=bit;crumb.title=target;crumb.onclick=()=>openFolder(target);nav.append(crumb)});$('#back').disabled=!folder.parent}
async function api(endpoint,payload){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error||'Could not save collection');collections=data;renderCollections();if(folder)renderFolder()}
async function toggleFavorite(item){try{await api('/api/favorites',{path:item.path,favorite:!isFavorite(item)})}catch(error){$('#status').textContent=error.message}}
async function addToPlaylist(item){const name=window.prompt('Playlist name:');if(!name?.trim())return;try{await api('/api/playlists',{name:name.trim(),path:item.path});$('#status').textContent=`Added to ${name.trim()}.`}catch(error){$('#status').textContent=error.message}}
async function createPlaylist(){const name=window.prompt('New playlist name:');if(!name?.trim())return;try{await api('/api/playlists',{name:name.trim()});$('#status').textContent=`Created ${name.trim()}.`}catch(error){$('#status').textContent=error.message}}
function collectionCard(item){const card=document.createElement('button');card.type='button';card.className='collection-card';card.innerHTML=`<span class="item-icon">${itemIcon(item)}</span><span><strong>${escape(item.name)}</strong><small>${escape(meta(item))}</small></span>`;card.onclick=()=>showItem(item);return card}
function renderCollections(){const favorites=$('#favorites'),playlists=$('#playlists');favorites.replaceChildren();playlists.replaceChildren();collections.favorites.forEach(item=>favorites.append(collectionCard(item)));$('#no-favorites').hidden=collections.favorites.length!==0;collections.playlists.forEach(list=>{const block=document.createElement('section');block.className='playlist-card';const heading=document.createElement('h3');heading.textContent=list.name;block.append(heading);if(!list.items.length){const empty=document.createElement('p');empty.textContent='No items yet.';block.append(empty)}list.items.forEach(item=>block.append(collectionCard(item)));playlists.append(block)});$('#no-playlists').hidden=collections.playlists.length!==0}
async function openFolder(path){$('#status').textContent='Opening folder…';try{const response=await fetch(`/api/browse?path=${encodeURIComponent(path)}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error||'Folder request failed');folder=data;$('#home-view').hidden=true;$('#browser-view').hidden=false;$('#preview').hidden=true;$('#viewer').replaceChildren();history.replaceState({path},'','#browse');breadcrumbs();renderFolder();$('#status').textContent='Ready — only this folder is loaded.'}catch(error){$('#status').textContent=error.message||'Could not open this folder.'}}
function showItem(item){return item.kind==='folder'?openFolder(item.path):openPreview(item)}
function openHome(){folder=null;$('#home-view').hidden=false;$('#browser-view').hidden=true;$('#preview').hidden=true;$('#viewer').replaceChildren();history.replaceState({},'','#home');$('#status').textContent='Choose a local drive or your Training Library.'}
function openPreview(item){const extension=item.extension;$('#preview-title').textContent=item.name;$('#preview').hidden=false;const viewer=$('#viewer');viewer.replaceChildren();let element;if(media.has(extension)){element=document.createElement('video');element.controls=true;element.autoplay=true;element.preload='metadata';let savedAt=0;element.onloadedmetadata=()=>{const saved=progress[item.path];if(saved&&saved.position>5&&saved.position<element.duration-5)element.currentTime=saved.position};const save=()=>{if(!Number.isFinite(element.currentTime)||!Number.isFinite(element.duration))return;savedAt=element.currentTime;progress[item.path]={position:element.currentTime,duration:element.duration};fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},keepalive:true,body:JSON.stringify({path:item.path,position:element.currentTime,duration:element.duration})}).catch(()=>{})};element.ontimeupdate=()=>{if(element.currentTime-savedAt>=5)save()};element.onpause=save;element.onended=save}else if(audio.has(extension)){element=document.createElement('audio');element.controls=true;element.autoplay=true}else if(images.has(extension)){element=document.createElement('img');element.alt=item.name}else if(embedded.has(extension)){element=document.createElement('iframe');element.title=`Preview of ${item.name}`}else{element=document.createElement('div');element.className='unsupported';element.innerHTML='<p>This format cannot be previewed directly by this browser.</p>'}if(element.tagName!=='DIV')element.src=url(item);viewer.append(element);const link=document.createElement('a');link.href=url(item);link.target='_blank';link.rel='noopener';link.textContent='Open or download file';link.className='open-file';viewer.append(link);$('#preview').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadDrives(){try{const [driveResponse,progressResponse,collectionResponse]=await Promise.all([fetch('/api/drives',{cache:'no-store'}),fetch('/api/progress',{cache:'no-store'}),fetch('/api/collections',{cache:'no-store'})]);const data=await driveResponse.json();if(!driveResponse.ok)throw Error();trainingPath=data.trainingPath||'';progress=progressResponse.ok?await progressResponse.json():{};collections=collectionResponse.ok?await collectionResponse.json():collections;const grid=$('#drive-grid');grid.replaceChildren();data.drives.forEach(drive=>{const card=document.createElement('button');card.type='button';card.className='drive-card';card.innerHTML=`<span class="drive-icon">▣</span><span><strong>${escape(drive.label)} <small>(${escape(drive.name)})</small></strong><small>${bytes(drive.free)} free of ${bytes(drive.total)}</small></span><span class="chevron">›</span>`;card.onclick=()=>openFolder(drive.path);grid.append(card)});$('#training-path').textContent=trainingPath;renderCollections();$('#status').textContent='Choose a local drive or your Training Library.'}catch{$('#status').textContent='Could not reach the library server.'}}
$('#search').oninput=renderFolder;$('#sort').onchange=renderFolder;$('#home').onclick=openHome;$('#back').onclick=()=>folder?.parent&&openFolder(folder.parent);$('#refresh-drives').onclick=loadDrives;$('#refresh-folder').onclick=()=>folder&&openFolder(folder.path);$('#training-shortcut').onclick=()=>openFolder(trainingPath);$('#new-playlist').onclick=createPlaylist;$('#close-preview').onclick=()=>{$('#preview').hidden=true;$('#viewer').replaceChildren()};loadDrives();
