let trainingPath='',folder=null,progress={},collections={favorites:[],playlists:[]},playlistItem=null,previewFromCollections=false;
const $=s=>document.querySelector(s),media=new Set(['mp4','webm','ogv','m4v','mov','mkv','avi','flv','wmv','mpeg','mpg','ts','m2ts','3gp']),audio=new Set(['mp3','wav','ogg','m4a','flac']),images=new Set(['jpg','jpeg','png','gif','webp','svg']),embedded=new Set(['pdf','txt','md','csv','json','html','htm']),direct=new Set(['mp4','webm','ogv','m4v','mov']);
const bytes=v=>v?new Intl.NumberFormat(undefined,{notation:v>999999?'compact':'standard',maximumFractionDigits:1}).format(v)+' B':'0 B',time=s=>{const n=Math.floor(s||0);return`${Math.floor(n/60)}m ${String(n%60).padStart(2,'0')}s`},escape=v=>{const e=document.createElement('span');e.textContent=v;return e.innerHTML},url=i=>`/files?path=${encodeURIComponent(i.path)}`,convertedUrl=key=>`/converted?key=${encodeURIComponent(key)}`;
function meta(i){const watched=progress[i.path];if(i.kind==='folder')return'Folder';if(media.has(i.extension)&&watched)return watched.duration&&watched.position>=watched.duration-5?`${i.extension} · completed`:`${i.extension} · watched ${time(watched.position)}`;return`${i.extension||'file'} · ${bytes(i.size)}`}
function icon(i){return i.kind==='folder'?'▰':media.has(i.extension)?'▶':audio.has(i.extension)?'♪':images.has(i.extension)?'▧':'•'}
function compare(a,b){const mode=$('#sort').value;if(mode==='name')return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'});if(mode==='modified')return b.modified.localeCompare(a.modified)||a.name.localeCompare(b.name);if(mode==='size')return b.size-a.size||a.name.localeCompare(b.name);const ak=a.kind==='folder'?'0-folder':`1-${a.extension||'other'}`,bk=b.kind==='folder'?'0-folder':`1-${b.extension||'other'}`;return ak.localeCompare(bk)||a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})}
const favorite=i=>collections.favorites.some(f=>f.path===i.path);
function actions(i){return i.kind==='folder'?`<span class="card-actions"><button class="collection-action favorite-action" type="button" title="${favorite(i)?'Remove from favorites':'Add to favorites'}">${favorite(i)?'★':'☆'}</button></span>`:`<span class="card-actions"><button class="collection-action playlist-action" type="button" title="Add to playlists">＋</button></span>`}
function renderFolder(){if(!folder)return;const term=$('#search').value.trim().toLowerCase(),items=folder.entries.filter(i=>!term||i.name.toLowerCase().includes(term)).sort(compare),catalog=$('#catalog');catalog.replaceChildren();items.forEach(i=>{const card=document.createElement('article');card.tabIndex=0;card.className=`item-card ${i.kind}`;card.innerHTML=`<span class="item-icon">${icon(i)}</span><span class="item-main"><strong>${escape(i.name)}</strong><small>${escape(meta(i))}</small></span>${actions(i)}${i.kind==='folder'?'<span class="chevron">›</span>':''}`;card.onclick=e=>{if(e.target.closest('.favorite-action'))return toggleFavorite(i);if(e.target.closest('.playlist-action'))return openPlaylistDialog(i);showItem(i)};card.onkeydown=e=>{if(e.key==='Enter')showItem(i)};catalog.append(card)});$('#empty').hidden=items.length!==0;$('#folder-summary').textContent=`${items.length} shown of ${folder.entries.length} visible items · refreshed ${new Date(folder.refreshedAt).toLocaleTimeString()}`}
function breadcrumbs(){const nav=$('#breadcrumbs');nav.replaceChildren();if(!folder)return;const bits=folder.path.replaceAll('/','\\').split('\\').filter(Boolean);let path=bits[0]?.endsWith(':')?`${bits[0]}\\`:'';bits.forEach((bit,index)=>{if(index>0)path+=`${bit}\\`;const target=index===0?`${bit}\\`:path.replace(/\\$/,'');const crumb=document.createElement('button');crumb.type='button';crumb.textContent=bit;crumb.onclick=()=>openFolder(target);nav.append(crumb)});$('#back').disabled=!folder.parent}
async function api(endpoint,payload){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error||'Could not save collection');collections=data;renderCollections();if(folder)renderFolder();return data}
async function toggleFavorite(i){try{await api('/api/favorites',{path:i.path,favorite:!favorite(i)})}catch(e){$('#status').textContent=e.message}}
function openPlaylistDialog(i){playlistItem=i;$('#playlist-item-name').textContent=i.name;$('#playlist-name').value='';const options=$('#playlist-options');options.replaceChildren();collections.playlists.forEach(list=>{const label=document.createElement('label');label.className='playlist-choice';label.innerHTML=`<input type="checkbox" value="${escape(list.name)}"> ${escape(list.name)} <small>${list.items.length} items</small>`;options.append(label)});$('#playlist-dialog').showModal()}
async function savePlaylistSelections(){if(!playlistItem)return;try{const newName=$('#playlist-name').value.trim();if(newName)await api('/api/playlists',{action:'create',name:newName});const selected=[...document.querySelectorAll('#playlist-options input:checked')].map(input=>input.value);if(newName)selected.push(newName);if(!selected.length)throw Error('Select or create at least one playlist.');await api('/api/playlists',{action:'add',names:[...new Set(selected)],path:playlistItem.path});$('#playlist-dialog').close();$('#status').textContent='Added to selected playlists.'}catch(e){$('#status').textContent=e.message}}
async function createPlaylist(){const name=window.prompt('New playlist name:');if(!name?.trim())return;try{await api('/api/playlists',{action:'create',name:name.trim()})}catch(e){$('#status').textContent=e.message}}
async function renamePlaylist(name){const updated=window.prompt('Rename playlist:',name);if(!updated?.trim()||updated===name)return;try{await api('/api/playlists',{action:'rename',oldName:name,name:updated.trim()})}catch(e){$('#status').textContent=e.message}}
async function deletePlaylist(name){if(!window.confirm(`Delete playlist “${name}”? Its files will not be deleted.`))return;try{await api('/api/playlists',{action:'delete',name})}catch(e){$('#status').textContent=e.message}}
async function removeItem(name,item){try{await api('/api/playlists',{action:'remove-item',name,path:item.path})}catch(e){$('#status').textContent=e.message}}
function collectionCard(i,remove){const card=document.createElement('div');card.className='collection-card';card.innerHTML=`<button class="collection-open" type="button"><span class="item-icon">${icon(i)}</span><span><strong>${escape(i.name)}</strong><small>${escape(meta(i))}</small></span></button>${remove?'<button class="collection-remove" type="button" title="Remove">×</button>':''}`;card.querySelector('.collection-open').onclick=()=>showItem(i);if(remove)card.querySelector('.collection-remove').onclick=remove;return card}
function renderCollections(){const favorites=$('#favorites'),playlists=$('#playlists');favorites.replaceChildren();playlists.replaceChildren();collections.favorites.forEach(i=>favorites.append(collectionCard(i,()=>toggleFavorite(i))));$('#no-favorites').hidden=collections.favorites.length!==0;collections.playlists.forEach(list=>{const block=document.createElement('section');block.className='playlist-card';block.innerHTML=`<div class="playlist-title"><h3>${escape(list.name)}</h3><span><button class="rename-playlist" type="button">Rename</button><button class="delete-playlist" type="button">Delete</button></span></div>`;block.querySelector('.rename-playlist').onclick=()=>renamePlaylist(list.name);block.querySelector('.delete-playlist').onclick=()=>deletePlaylist(list.name);if(!list.items.length){const empty=document.createElement('p');empty.textContent='No files yet.';block.append(empty)}list.items.forEach(i=>block.append(collectionCard(i,()=>removeItem(list.name,i))));playlists.append(block)});$('#no-playlists').hidden=collections.playlists.length!==0}
async function openFolder(path){$('#status').textContent='Opening folder…';try{const response=await fetch(`/api/browse?path=${encodeURIComponent(path)}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error||'Folder request failed');folder=data;$('#home-view').hidden=true;$('#browser-view').hidden=false;$('#preview').hidden=true;$('#viewer').replaceChildren();history.replaceState({path},'','#browse');breadcrumbs();renderFolder();$('#status').textContent='Ready — only this folder is loaded.'}catch(e){$('#status').textContent=e.message||'Could not open this folder.'}}
function showItem(i){return i.kind==='folder'?openFolder(i.path):openPreview(i)}
function openHome(){folder=null;$('#home-view').hidden=false;$('#browser-view').hidden=true;$('#preview').hidden=true;$('#viewer').replaceChildren();history.replaceState({},'','#home');$('#status').textContent='Choose a local drive or your Training Library.'}
async function preparePlayback(i,video,status){
  if(video.dataset.preparing)return;
  video.dataset.preparing='true';status.hidden=false;
  try{
    for(let attempt=0;attempt<720;attempt++){
      status.textContent=attempt?'Still preparing a seekable MP4…':'Preparing a seekable MP4 with full controls…';
      const response=await fetch(`/api/prepare?path=${encodeURIComponent(i.path)}`,{cache:'no-store'}),data=await response.json();
      if(!response.ok)throw Error(data.error||'Could not prepare this video.');
      if(data.state==='ready'){
        status.hidden=true;video.src=convertedUrl(data.key);video.load();video.play().catch(()=>{});return;
      }
      await new Promise(resolve=>setTimeout(resolve,4000));
    }
    throw Error('Video preparation timed out.');
  }catch(error){status.textContent=error.message||'Could not prepare this video.';video.dataset.preparing='';}
}
function openPreview(i){
  if($('#browser-view').hidden){previewFromCollections=true;$('#home-view').hidden=true;$('#browser-view').hidden=false;$('#catalog').replaceChildren();$('#folder-summary').textContent='Playlist playback';}
  const ext=i.extension;$('#preview-title').textContent=i.name;$('#preview').hidden=false;const viewer=$('#viewer');viewer.replaceChildren();let element;
  if(media.has(ext)){
    const status=document.createElement('p');status.className='player-status';status.hidden=true;viewer.append(status);
    element=document.createElement('video');element.controls=true;element.autoplay=true;element.preload='metadata';let savedAt=0;
    const fallback=()=>preparePlayback(i,element,status);element.onerror=fallback;
    element.onloadedmetadata=()=>{const saved=progress[i.path];if(saved&&saved.position>5&&saved.position<element.duration-5)element.currentTime=saved.position};
    const save=()=>{if(!Number.isFinite(element.currentTime)||!Number.isFinite(element.duration))return;savedAt=element.currentTime;progress[i.path]={position:element.currentTime,duration:element.duration};fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},keepalive:true,body:JSON.stringify({path:i.path,position:element.currentTime,duration:element.duration})}).catch(()=>{})};
    element.ontimeupdate=()=>{if(element.currentTime-savedAt>=5)save()};element.onpause=save;element.onended=save;
    if(direct.has(ext))element.src=url(i);else preparePlayback(i,element,status);
  }else if(audio.has(ext)){element=document.createElement('audio');element.controls=true;element.autoplay=true;element.src=url(i)}else if(images.has(ext)){element=document.createElement('img');element.alt=i.name;element.src=url(i)}else if(embedded.has(ext)){element=document.createElement('iframe');element.title=`Preview of ${i.name}`;element.src=url(i)}else{element=document.createElement('div');element.className='unsupported';element.innerHTML='<p>This format cannot be previewed directly by this browser.</p>'}
  viewer.append(element);const link=document.createElement('a');link.href=url(i);link.target='_blank';link.rel='noopener';link.textContent='Open or download original file';link.className='open-file';viewer.append(link);$('#preview').scrollIntoView({behavior:'smooth',block:'start'});
}
async function loadDrives(){try{const [driveResponse,progressResponse,collectionResponse]=await Promise.all([fetch('/api/drives',{cache:'no-store'}),fetch('/api/progress',{cache:'no-store'}),fetch('/api/collections',{cache:'no-store'})]);const data=await driveResponse.json();if(!driveResponse.ok)throw Error();trainingPath=data.trainingPath||'';progress=progressResponse.ok?await progressResponse.json():{};collections=collectionResponse.ok?await collectionResponse.json():collections;const grid=$('#drive-grid');grid.replaceChildren();data.drives.forEach(drive=>{const card=document.createElement('button');card.type='button';card.className='drive-card';card.innerHTML=`<span class="drive-icon">▣</span><span><strong>${escape(drive.label)} <small>(${escape(drive.name)})</small></strong><small>${bytes(drive.free)} free of ${bytes(drive.total)}</small></span><span class="chevron">›</span>`;card.onclick=()=>openFolder(drive.path);grid.append(card)});$('#training-path').textContent=trainingPath;renderCollections();$('#status').textContent='Choose a local drive or your Training Library.'}catch{$('#status').textContent='Could not reach the library server.'}}
$('#search').oninput=renderFolder;$('#sort').onchange=renderFolder;$('#home').onclick=openHome;$('#back').onclick=()=>folder?.parent&&openFolder(folder.parent);$('#refresh-drives').onclick=loadDrives;$('#refresh-folder').onclick=()=>folder&&openFolder(folder.path);$('#training-shortcut').onclick=()=>openFolder(trainingPath);$('#new-playlist').onclick=createPlaylist;$('#save-playlists').onclick=savePlaylistSelections;$('#close-preview').onclick=()=>{if(previewFromCollections){previewFromCollections=false;openHome()}else{$('#preview').hidden=true;$('#viewer').replaceChildren()}};loadDrives();
